global:
  scrape_interval: 15s
  evaluation_interval: 15s
  external_labels:
    monitor: 'ror-trader-monitor'

scrape_configs:
  - job_name: 'ror-trader-api'
    static_configs:
      - targets: ['host.docker.internal:4000']
    metrics_path: '/metrics'

  - job_name: 'ror-trader-webhook'
    static_configs:
      - targets: ['host.docker.internal:4001']
    metrics_path: '/metrics'

  - job_name: 'redis'
    static_configs:
      - targets: ['redis:6379']

  - job_name: 'postgres'
    static_configs:
      - targets: ['postgres:5432']

  - job_name: 'node-exporter'
    static_configs:
      - targets: ['host.docker.internal:9100']

alerting:
  alertmanagers:
    - static_configs:
        - targets: []

rule_files:
  # - '/etc/prometheus/alerts/*.yml'
